before_install:
  - gem update bundler
  - bundle --version
language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
env:
  - rails=3.1.12
  - rails=3.2.18
  - rails=4.0.5
  - rails=4.1.1
addons:
  code_climate:
    repo_token: f010f83a5eb6671c85aaa0aec44c1fd43404537a4f4898d1b9ab248ac8a1487d
